# DB config
DB_SCHEMA: mailrepicients
DB_HOST: localhost
DB_PORT: 3306
DB_USERNAME: root
DB_PASSWORD: hungto228

server:
 port: 8080

spring:
 #mysql config
 datasource:
  url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
   format_sql: true
  database-platform=org:
   hibernate:
    dialect:
     MySQL5InnoDBDialect
 mail:
  port: 587
  host: smtp.googlemail.com
  username: hungto2288@gmail.com
  password: baybay99
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true



EMAIL_SUBJECT: SSS3334đâsfadfad
EMAIL_CONTENT: SSSáđấ
PATH_IMAGE: C:/Users/Admin/Desktop/imageapp/dangnhap.png
NAME_FILE: anhdangnhhap



